name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Check formatting
        run: deno fmt --check

      - name: Lint code
        run: deno lint

      - name: Type check
        run: deno task check

      - name: Run unit tests
        run: deno task db:push && deno task test

      - name: Install Playwright browsers
        run: deno task e2e:install

      - name: Install Playwright Ubuntu dependencies
        run: deno run -A npm:playwright@^1.56.1 install-deps chromium

      - name: Run E2E tests (Playwright)
        env:
          NODE_ENV: development
          FRONTEND_PORT: 3000
        run: deno task e2e

      - name: cSpell
        run: deno task spell:check
